In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('~/IPL crunch/data/att_0_1778303821_c3a907.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/home/lycoriz/IPL crunch/data/att_0_1778303821_c3a907.csv'

In [3]:
df.head()

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,...,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
1,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
2,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,4,0,4,0,0,0,0,NaN,NaN
3,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
4,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,2,2,2,0,0,0,NaN,NaN

In [4]:
df.columns.to_list()

['match_id',
 'date',
 'season',
 'event',
 'venue',
 'city',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'win_by_runs',
 'win_by_wickets',
 'player_of_match',
 'innings',
 'batting_team',
 'over',
 'ball',
 'batter',
 'bowler',
 'non_striker',
 'runs_batter',
 'runs_extras',
 'runs_total',
 'extras_wides',
 'extras_noballs',
 'extras_byes',
 'extras_legbyes',
 'wicket_kind',
 'wicket_player_out']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289673 entries, 0 to 289672
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           289673 non-null  int64
 1   date               289673 non-null  object
 2   season             289673 non-null  object
 3   event              289673 non-null  object
 4   venue              289673 non-null  object
 5   city               277276 non-null  object
 6   team1              289673 non-null  object
 7   team2              289673 non-null  object
 8   toss_winner        289673 non-null  object
 9   toss_decision      289673 non-null  object
 10  winner             289673 non-null  object
 11  win_by_runs        133547 non-null  float64
 12  win_by_wickets     151146 non-null  float64
 13  player_of_match    288845 non-null  object
 14  innings            289673 non-null  int64
 15  batting_team       289673 non-null  object
 16  over               289673 non-null  int64
 17  ball               289673 non-null  int64
 18  batter             289673 non-null  object
 19  bowler             289673 non-null  object
 20  non_striker        289673 non-null  object
 21  runs_batter        289673 non-null  int64
 22  runs_extras        289673 non-null  int64
 23  runs_total         289673 non-null  int64
 24  extras_wides       289673 non-null  int64
 25  extras_noballs     289673 non-null  int64
 26  extras_byes        289673 non-null  int64
 27  extras_legbyes     289673 non-null  int64
 28  wicket_kind        14406 non-null   object
 29  wicket_player_out  14406 non-null   object
dtypes: float64(2), int64(11), object(17)
memory usage: 66.3+ MB

In [6]:
df.describe()

,match_id,win_by_runs,win_by_wickets,innings,over,ball,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes
count,2.896730e+05,133547.000000,151146.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000,289673.000000
mean,9.654832e+05,30.217766,6.115266,1.482793,9.190563,3.628167,1.285477,0.068184,1.353661,0.039565,0.004277,0.004705,0.019601
std,3.911715e+05,26.530801,1.823510,0.502495,5.680221,1.818353,1.659483,0.342671,1.645469,0.255822,0.068964,0.114363,0.190069
min,3.359820e+05,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483650e+05,11.000000,5.000000,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.082626e+06,22.000000,6.000000,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1.304085e+06,41.000000,7.000000,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,1.529292e+06,146.000000,10.000000,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,5.000000,5.000000,4.000000,5.000000

In [7]:
df.isnull().sum()

match_id                  0
date                      0
season                    0
event                     0
venue                     0
city                  12397
team1                     0
team2                     0
toss_winner               0
toss_decision             0
winner                    0
win_by_runs          156126
win_by_wickets       138527
player_of_match         828
innings                   0
batting_team              0
over                      0
ball                      0
batter                    0
bowler                    0
non_striker               0
runs_batter               0
runs_extras               0
runs_total                0
extras_wides              0
extras_noballs            0
extras_byes               0
extras_legbyes            0
wicket_kind          275267
wicket_player_out    275267
dtype: int64