In [25]:
import os
import sys
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
from pathlib import Path
sys.path.append(os.path.abspath(".."))
import src.cleaning_and_preprocessing as proc
# 1. Load the autoreload extension
%load_ext autoreload
# 2. Instruct it to reload all modules every time you execute a cell
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
file_path = Path('../data/raw/ipl-ball-by-ball-dataset.csv')
df = pd.read_csv(file_path,low_memory=False)

In [3]:
df.head(2)

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,392201,2009-04-30,2009,Indian Premier League,SuperSport Park,Centurion,Deccan Chargers,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,0,6,DP Nannes,1,Deccan Chargers,0,1,AC Gilchrist,DP Nannes,HH Gibbs,0,0,0,0,0,0,0,NaN,NaN
1,392201,2009-04-30,2009,Indian Premier League,SuperSport Park,Centurion,Deccan Chargers,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,0,6,DP Nannes,1,Deccan Chargers,0,2,AC Gilchrist,DP Nannes,HH Gibbs,0,0,0,0,0,0,0,NaN,NaN

In [4]:
print(df.columns.to_list())
print(len(df.columns.to_list()))

['match_id', 'date', 'season', 'event', 'venue', 'city', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'innings', 'batting_team', 'over', 'ball', 'batter', 'bowler', 'non_striker', 'runs_batter', 'runs_extras', 'runs_total', 'extras_wides', 'extras_noballs', 'extras_byes', 'extras_legbyes', 'wicket_kind', 'wicket_player_out']
30

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           295732 non-null  int64
 1   date               295732 non-null  object
 2   season             295732 non-null  object
 3   event              295732 non-null  object
 4   venue              295732 non-null  object
 5   city               295732 non-null  object
 6   team1              295732 non-null  object
 7   team2              295732 non-null  object
 8   toss_winner        295732 non-null  object
 9   toss_decision      295732 non-null  object
 10  winner             295732 non-null  object
 11  win_by_runs        295732 non-null  int64
 12  win_by_wickets     295732 non-null  int64
 13  player_of_match    294904 non-null  object
 14  innings            295732 non-null  int64
 15  batting_team       295732 non-null  object
 16  over               295732 non-null  int64
 17  ball               295732 non-null  int64
 18  batter             295732 non-null  object
 19  bowler             295732 non-null  object
 20  non_striker        295732 non-null  object
 21  runs_batter        295732 non-null  int64
 22  runs_extras        295732 non-null  int64
 23  runs_total         295732 non-null  int64
 24  extras_wides       295732 non-null  int64
 25  extras_noballs     295732 non-null  int64
 26  extras_byes        295732 non-null  int64
 27  extras_legbyes     295732 non-null  int64
 28  wicket_kind        14705 non-null   object
 29  wicket_player_out  14705 non-null   object
dtypes: int64(13), object(17)
memory usage: 67.7+ MB

In [6]:
df.isnull().sum()

match_id                  0
date                      0
season                    0
event                     0
venue                     0
city                      0
team1                     0
team2                     0
toss_winner               0
toss_decision             0
winner                    0
win_by_runs               0
win_by_wickets            0
player_of_match         828
innings                   0
batting_team              0
over                      0
ball                      0
batter                    0
bowler                    0
non_striker               0
runs_batter               0
runs_extras               0
runs_total                0
extras_wides              0
extras_noballs            0
extras_byes               0
extras_legbyes            0
wicket_kind          281027
wicket_player_out    281027
dtype: int64

In [14]:
# Combine team1 and team2 columns, get unique values, and drop any nulls
unique_teams = pd.concat([df['team1'], df['team2']]).dropna().unique()

# Sort them alphabetically to  spot variations 
unique_teams.sort()

# Print the list
print(f"Total Unique Team Entries Found: {len(unique_teams)}\n")
print("--- Team List ---")
for team in unique_teams:
    print(team)

Total Unique Team Entries Found: 15

--- Team List ---
Chennai Super Kings
Deccan Chargers
Delhi Capitals
Gujarat Lions
Gujarat Titans
Kochi Tuskers Kerala
Kolkata Knight Riders
Lucknow Super Giants
Mumbai Indians
Pune Warriors
Punjab Kings
Rajasthan Royals
Rising Pune Supergiant
Royal Challengers Bengaluru
Sunrisers Hyderabad

In [34]:
df = proc.standardize_teams(df)
# changes team names to current ones
# 'Delhi Daredevils': 'Delhi Capitals'
# Kings XI Punjab': 'Punjab Kings'
# 'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
#'Rising Pune Supergiants': 'Rising Pune Supergiant'

Teams reduced to 15

In [29]:
# Get unique cities, drop nulls, and sort alphabetically
unique_cities = df['city'].dropna().unique()
unique_cities.sort()

print(f"Total Unique Cities Found: {len(unique_cities)}\n")
print("--- City List ---")
for city in unique_cities:
    print(city)

Total Unique Cities Found: 34

--- City List ---
Abu Dhabi
Ahmedabad
Bengaluru
Bloemfontein
Cape Town
Centurion
Chandigarh
Chennai
Cuttack
Delhi
Dharamsala
Dubai
Durban
East London
Guwahati
Hyderabad
Indore
Jaipur
Johannesburg
Kanpur
Kimberley
Kochi
Kolkata
Lucknow
Mumbai
Nagpur
Navi Mumbai
Port Elizabeth
Pune
Raipur
Rajkot
Ranchi
Sharjah
Visakhapatnam

In [ ]:
df = proc.standardize_cities(df)
# fix city names
# 'Bangalore': 'Bengaluru',
# 'Mohali': 'Chandigarh',
# 'New Chandigarh': 'Chandigarh'

In [35]:
# Get unique venues, drop nulls, and sort alphabetically
unique_venues = df['venue'].dropna().unique()
unique_venues.sort()

print(f"Total Unique Venues Found: {len(unique_venues)}\n")
print("--- Venue List ---")
for venue in unique_venues:
    print(venue)

Total Unique Venues Found: 37

--- Venue List ---
Arun Jaitley Stadium
Barabati Stadium
Barsapara Cricket Stadium, Guwahati
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
Brabourne Stadium
Buffalo Park
De Beers Diamond Oval
Dr DY Patil Sports Academy
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium
Dubai International Cricket Stadium
Eden Gardens
Green Park
Himachal Pradesh Cricket Association Stadium
Holkar Cricket Stadium
JSCA International Stadium Complex
Kingsmead
M Chinnaswamy Stadium
MA Chidambaram Stadium
Maharaja Yadavindra Singh International Cricket Stadium
Maharashtra Cricket Association Stadium
Narendra Modi Stadium
Nehru Stadium
New Wanderers Stadium
Newlands
OUTsurance Oval
Punjab Cricket Association IS Bindra Stadium
Rajiv Gandhi International Stadium
Saurashtra Cricket Association Stadium
Sawai Mansingh Stadium
Shaheed Veer Narayan Singh International Stadium
Shaheed Veer Narayan Singh International Stadium, Raipur
Sharjah Cricket Stadium
Sheikh Zayed Stadium
St George's Park
SuperSport Park
Vidarbha Cricket Association Stadium, Jamtha
Wankhede Stadium

In [32]:
df = proc.standardize_venues(df)
#fixes multiple venue names

Venues reduced from 59 to 37

In [36]:
print(df['season'].unique())

['2009' '2020/21' '2018' '2022' '2017' '2016' '2025' '2019' '2026' '2015'
 '2013' '2024' '2021' '2007/08' '2023' '2011' '2014' '2012' '2009/10']

In [37]:
df = proc.format_dates_and_sort(df)

In [43]:
print(sorted(df['season'].unique()))

[2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

In [44]:
df.head(1)

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,335982,2008-04-18,2008,Indian Premier League,M Chinnaswamy Stadium,Bengaluru,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,Kolkata Knight Riders,140,0,BB McCullum,1,Kolkata Knight Riders,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0,0,0,1,NaN,NaN

In [45]:
df.tail(1)

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,winner,win_by_runs,win_by_wickets,player_of_match,innings,batting_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
295731,1535465,2026-05-31,2026,Indian Premier League,Narendra Modi Stadium,Ahmedabad,Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Royal Challengers Bengaluru,0,5,V Kohli,2,Royal Challengers Bengaluru,17,6,V Kohli,Arshad Khan,JM Sharma,6,0,6,0,0,0,0,NaN,NaN

In [46]:
df = proc.handle_missing_values(df)
# Fill empty wicket fields with logical text and unawarded player of the matches clearly

In [70]:
"""from thefuzz import process

# 1. Gather every unique player name from all relevant columns
player_cols = ['batter', 'bowler', 'non_striker', 'player_of_match', 'wicket_player_out']
all_names = pd.concat([df[col] for col in player_cols]).dropna().unique()

# 2. Create a list to store our potential typos
potential_typos = []
processed_names = set() # To avoid checking the same name twice

print("Scanning for similar names...")

for name in all_names:
    if name not in processed_names:
        # Extract the top 3 matches for 'name' from the master list
        similar_names = process.extract(name, all_names, limit=4)
        
        # Keep matches that score between 85 and 99 
        # (100 is an exact match, below 85 is usually a different person)
        high_matches = [match for match in similar_names if 87 <= match[1] < 100]
        
        if high_matches:
            print(f"\nTarget Name: {name}")
            for match_name, score in high_matches:
                print(f" -> Found: '{match_name}' (Score: {score})")
                processed_names.add(match_name) # Mark as processed
                
        processed_names.add(name)"""

'from thefuzz import process\n\n# 1. Gather every unique player name from all relevant columns\nplayer_cols = [\'batter\', \'bowler\', \'non_striker\', \'player_of_match\', \'wicket_player_out\']\nall_names = pd.concat([df[col] for col in player_cols]).dropna().unique()\n\n# 2. Create a list to store our potential typos\npotential_typos = []\nprocessed_names = set() # To avoid checking the same name twice\n\nprint("Scanning for similar names...")\n\nfor name in all_names:\n    if name not in processed_names:\n        # Extract the top 3 matches for \'name\' from the master list\n        similar_names = process.extract(name, all_names, limit=4)\n        \n        # Keep matches that score between 85 and 99 \n        # (100 is an exact match, below 85 is usually a different person)\n        high_matches = [match for match in similar_names if 87 <= match[1] < 100]\n        \n        if high_matches:\n            print(f"\nTarget Name: {name}")\n            for match_name, score in high_matches:\n                print(f" -> Found: \'{match_name}\' (Score: {score})")\n                processed_names.add(match_name) # Mark as processed\n                \n        processed_names.add(name)'

In [47]:
df = proc.standardize_player_names(df)

In [48]:
# This should print a long list of zeros!
print(df.isna().sum())

match_id             0
date                 0
season               0
event                0
venue                0
city                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               0
win_by_runs          0
win_by_wickets       0
player_of_match      0
innings              0
batting_team         0
over                 0
ball                 0
batter               0
bowler               0
non_striker          0
runs_batter          0
runs_extras          0
runs_total           0
extras_wides         0
extras_noballs       0
extras_byes          0
extras_legbyes       0
wicket_kind          0
wicket_player_out    0
dtype: int64

In [ ]:
# Step 1: Ensure the directory exists
output_dir = Path('../data/processed')

# Step 2: Define the exact file path
output_file = output_dir / 'ipl_cleaned.csv'

# Step 3: Export the DataFrame
# VERY IMPORTANT: index=False prevents pandas from writing the row numbers as a new column
df.to_csv(output_file, index=False)

print(f"Success! Clean data saved to: {output_file}")

Success! Clean data saved to: ../data/processed/ipl_cleaned.csv